export const INCREAMENT_COUNTER = 'INCREAMENT_COUNTER'
export const DECREAMENT_COUNTER = 'DECREAMENT_COUNTER' 

export const GET_MEDICINESDATA = 'GET_MEDICINESDATA'

export const LOADING_MEDICINES = 'LOADING_MEDICINES'
export const ERROR_MEDICINES = 'ERROR_MEDICINES'