export const INCREAMENT_COUNTER = 'INCREAMENT_COUNTER'
export const DECREAMENT_COUNTER = 'DECREAMENT_COUNTER' 

export const GET_MEDICINESDATA = 'GET_MEDICINESDATA'
export const ADD_MEDICINESDATA = 'ADD_MEDICINESDATA'
export const DELETE_MEDICINESDATA = 'DELETE_MEDICINESDATA'
export const UPDATE_MEDICINESDATA = 'UPDATE_MEDICINESDATA'

export const GET_PATIENTSDATA = 'GET_PATIENTSDATA'
export const ADD_PATIENTSDATA = 'ADD_PATIENTSDATA'
export const DELETE_PATIENTSDATA = 'DELETE_PATIENTSDATA'

export const GET_DOCTERDATA = 'GET_DOCTERDATA'
export const ADD_DOCTERDATA = 'ADD_DOCTERDATA'
export const DELETE_DOCTERDATA = 'DELETE_DOCTERDATA'

export const LOADING_MEDICINES = 'LOADING_MEDICINES'
export const ERROR_MEDICINES = 'ERROR_MEDICINES'

export const LOADING_PATIENTS = 'LOADING_PATIENTS'
export const ERROR_PATIENTS = 'ERROR_PATIENTS'

export const LOADING_DOCTER = 'LOADING_DOCTER'
export const ERROR_DOCTER = 'ERROR_DOCTER'
